logging:
  config: classpath:logback-spring.xml

redis:
  host: localhost
  port: 6379
  timeout: 3
  password: 123456
  poolMaxTotal: 10
  poolMaxIdle: 10
  poolMaxWait: 3

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mine?characterEncoding=utf8&useSSL=false
    username: root
    password: llovejava1234
    type: com.alibaba.druid.pool.DruidDataSource
# 配置打印sql语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl